# Generated by Django 4.2.4 on 2023-09-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RP_to_text', '0002_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
