# Generated by Django 4.2.4 on 2023-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RP_to_text', '0003_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInformation',
            fields=[
                ('date_revue_presse', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('journal_type', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article_informations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageLabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_revue_presse', models.CharField(max_length=255)),
                ('num_page', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pagelabels',
                'managed': False,
            },
        ),
    ]
